# Download base image
FROM node:14

LABEL maintainer="prasad.rohan93@gmail.com"
LABEL description="Development image for node based project."

RUN npm install -g pm2

EXPOSE 3000

CMD tail -f /dev/null